[package]
name = "redis-rs-macro"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
redis-test = "0.2"
redis = "0.23"